version: 2
jobs:
    build:

        working_directory: ~/devel

        docker:
            - image: circleci/openjdk:11-jdk-browsers

        steps:
            - checkout

            - restore_cache:
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            - run: mvn dependency:go-offline

            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            - run: mvn test

            - run: mvn package

            - store_test_results:
                  path: target/surefire-reports

            - store_artifacts:
                  path: target/bmpinfo.jar

            - store_artifacts:
                  path: target/html_decoder.jar

            - store_artifacts:
                  path: target/invert.jar

            - store_artifacts:
                  path: target/join.jar

            - store_artifacts:
                  path: target/mini_dictionary.jar

            - store_artifacts:
                  path: target/prime_numbers_generator.jar

            - store_artifacts:
                  path: target/radix.jar

            - store_artifacts:
                  path: target/url_parser.jar

            - store_artifacts:
                  path: target/vector.jar
