version: 2
jobs:
    build:

        working_directory: ~/devel

        docker:
            - image: circleci/openjdk:11-jdk-browsers

        steps:
            - checkout

            - restore_cache:
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            - run: mvn dependency:go-offline

            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            - run: mvn test

            - run: mvn package

            - run:
                name: Copy JARs
                command: |
                    mkdir target/jars
                    cp target/*.jar target/jars

            - store_test_results:
                  path: target/surefire-reports

            - store_artifacts:
                  path: target/jars
